language: python
python:
 - "2.7"

install:
 - pip install blended
script: blended build
after_success: tail -n +3 deployed_readme.md > build/Readme.md
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: ./build
  repo: ArtOfIllusion/ArtOfIllusion.github.io
  target_branch: master
  github_token: $GHPages_Token
  on:
    branch: master
