blended_version = 5.0

# Configuration is automatically generated by Blended (http://jmroper.com/blended), feel free to edit any values below
website_name = "Art of Illusion"
website_description = "Open Source 3D Modeling and Rendering Studio"
website_description_long = ""
website_license = "2017 {author_name}"
website_language = "en-US"
website_url = ""

author_name = "The {website_name} Team"
author_bio = ""

home_page_list = True

plugins = [] # Place all needed plugins in here
custom_variables = {"aoi_version": "3.0.3"} # Place all custom variables in here

minify_css = True
minify_js = True

# The following values are used for FTP uploads
ftp_server = "localhost"
ftp_username = "user"
ftp_password = "pass"
ftp_port = 21
ftp_upload_path = "public_html/myWebsite"
