blended_version = 4.1

# Configuration is automatically generated by Blended, feel free to edit any values below
website_name = "Art of Illusion"
website_description = "Open Source 3D Modeling and Rendering Studio"
website_description_long = "" # Use for things like author bio on a blog
website_license = "2017 The Art of Illusion Team"
author_name = "The Art of Illusion Team"
website_language = "en"
home_page_list = "yes"

plugins = [] # Place all needed plugins in here

# The following values are used for FTP uploads
ftp_server = "localhost"
ftp_username = "user"
ftp_password = "pass"
ftp_port = 21
ftp_upload_path = "public_html/myWebsite"
